name: Publish Preview

on:
  pull_request:
    branches:
      - master

jobs:
  publish-previews:
    name: Publish Preview Packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish PR Preview
      uses: thefrontside/actions/publish-pr-preview@v1.2
      with:
        NPM_PUBLISH: npm run pack:publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN:  ${{ secrets.NPM_AUTH_TOKEN }}
