name: Publish Release

on:
  push:
    branches:
      - master
      - release-*

jobs:
  publish:
    name: Synchronize with NPM
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Tag and Publish
      uses: minkimcello/actions/synchronize-with-npm@mk/extending-publishing
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      with:
        NPM_PUBLISH: bin/publish