name: Publish Release

on:
  push:
    branches:
      - master

jobs:
  publish-releases:
    name: Publish Releases
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create Release Pull Request
      uses: changesets/action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish Releases
      uses: thefrontside/actions/synchronize-with-npm@v1.7
      with:
        before_all: yarn prepack
        npm_publish: yarn publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
