name: Synchronize NPM Tags

on:
  delete

jobs:
  clean:
    name: Synchronize NPM Tags
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: minkimcello/actions/synchronize-npm-tags@mk/publish-pr-preview
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}