name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 5
    name: all pkgs on ${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: cache node_modules
        uses: actions/cache@v2
        # cache node_modules based on lockfile which can change
        # when there is no explicit change in package.json
        # and prevents cache bust when scripts or metadata is changed
        # which does not effect the node_modules themselves
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - run: yarn prepack
      - name: test
        run: yarn test
      - name: test types in effection
        run: yarn workspace effection test:types
